# Same as Black.
line-length = 110
indent-width = 4

# Assume Python 3.9
target-version = "py39"

[lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
select = ["ALL"]
ignore = [
    "INP001",
    "I001",
    "DTZ001",
    "ANN",
    "G004",
    "D401",
    "RET504",
    "ISC001",
    "N806",
    "N803",
    "PD004",
    "PD003",
    "TRY003",
    "ARG002",
    # Literals
    "C408",
    # Trailing comma missing
    "COM812",
    # Private members accessed
    "SLF001",
    # Unnecessary `map` usage
    "C417",
    # Usage of old path functions
    "PTH",
    "FIX",
    # How to write TODOs
    "TD",
    # Use `key in dict` instead of `key in dict.keys()`
    "SIM118",
    "PLR0915",
    "PLR0913",
    "PD901",
    "PD011",
    "C403",
    "SLOT000",
    "PD002",
    "PD008",
    "PLR1714",
    "SIM",
    "B011",
    "PT015",
    "C411",
    "RUF",
    "FA100",
    "TRY002",
    "B904",
    "PLW2901",
    "TID",
    "D",
    "NPY",
    "FBT",
    "RET",
    "PLR",
    "C901",
    "UP030",
    "PERF203",
    "PERF401",
    "EM",
    "TRY4",
    "BLE001",
    "ARG",
    "PYI",
    "S105",
    "FLY002",
    "PERF102",
    "TRY201",
    "C416",
    "N801",
    "B007",
    "PD010",
    "PLW0603",
    "DTZ005",
    "PERF403",
    "ICN001",
    "B023",
    "TRY",
    "E501",
    "S307",
    "N818",
    "S107",
    "PLW1508",
    "LOG002",
    "UP",
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.pydocstyle]
convention = "numpy"

[lint.per-file-ignores]
"workshops/rag_concealment_personal_data/new_config_1.25.py" = ["Q000"]
"workshops/example_ml.ipynb" = ["T20", "S"]

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

# Enable auto-formatting of code examples in docstrings. Markdown,
# reStructuredText code/literal blocks and doctests are all supported.
#
# This is currently disabled by default, but it is planned for this
# to be opt-out in the future.
docstring-code-format = false

# Set the line length limit used when formatting code snippets in
# docstrings.
#
# This only has an effect when the `docstring-code-format` setting is
# enabled.
docstring-code-line-length = "dynamic"
