"""Config for data dags"""


class Config:
    VAR_DATASET_ROOT_DIR = "DATASET_ROOT_DIR"
    VAR_DATASET_DIR_NAME = "DATASET_DIR_NAME"
    VAR_DATASET_FILE_NAME = "DATASET_FILE_NAME"

    VAR_EVALUATION_ROOT_DIR = "EVALUATION_ROOT_DIR"
    VAR_EVALUATION_DIR_NAME = "EVALUATION_DIR_NAME"
